# Form implementation generated from reading ui file 'main_ui.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(462, 680)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(194, 194, 194);\n"
"QWidget {\n"
"    background-color: #f0f0f0;  /* светло-серый фон */\n"
"    color: #000000;  /* черный текст */\n"
"}\n"
"QPushButton {\n"
"    background-color: #d3d3d3;  /* светло-серая кнопка */\n"
"    color: #000000;  /* черный текст */\n"
"    border: 1px solid #000000;  /* черная рамка */\n"
"}\n"
"QLineEdit {\n"
"    background-color: #ffffff;  /* белое текстовое поле */\n"
"    color: #000000;  /* черный текст */\n"
"    border: 1px solid #000000;  /* черная рамка */\n"
"}\n"
"QRadioButton {\n"
"    background-color: #f0f0f0;  /* фон радиокнопок */\n"
"    color: #000000;  /* черный текст */\n"
"}\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(parent=self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(20, 10, 431, 661))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.chosen_files_field = QtWidgets.QVBoxLayout()
        self.chosen_files_field.setObjectName("chosen_files_field")
        self.main_label = QtWidgets.QLabel(parent=self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.main_label.setFont(font)
        self.main_label.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.PreventContextMenu)
        self.main_label.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.main_label.setStyleSheet("background-color: rgb(214, 214, 214);")
        self.main_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.main_label.setWordWrap(True)
        self.main_label.setObjectName("main_label")
        self.chosen_files_field.addWidget(self.main_label)
        self.chosen_files_label = QtWidgets.QLabel(parent=self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.chosen_files_label.setFont(font)
        self.chosen_files_label.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.PreventContextMenu)
        self.chosen_files_label.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.chosen_files_label.setStyleSheet("background-color: rgb(214, 214, 214);")
        self.chosen_files_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.chosen_files_label.setWordWrap(True)
        self.chosen_files_label.setObjectName("chosen_files_label")
        self.chosen_files_field.addWidget(self.chosen_files_label)
        self.chosen_fiels_textEdit = QtWidgets.QTextEdit(parent=self.verticalLayoutWidget_2)
        self.chosen_fiels_textEdit.setEnabled(False)
        self.chosen_fiels_textEdit.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhNoEditMenu)
        self.chosen_fiels_textEdit.setReadOnly(True)
        self.chosen_fiels_textEdit.setTabStopDistance(79.0)
        self.chosen_fiels_textEdit.setObjectName("chosen_fiels_textEdit")
        self.chosen_files_field.addWidget(self.chosen_fiels_textEdit)
        self.choose_files_btn = QtWidgets.QPushButton(parent=self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.choose_files_btn.setFont(font)
        self.choose_files_btn.setStyleSheet("background-color: rgb(214, 214, 214);")
        self.choose_files_btn.setObjectName("choose_files_btn")
        self.chosen_files_field.addWidget(self.choose_files_btn)
        self.files_number_field = QtWidgets.QHBoxLayout()
        self.files_number_field.setObjectName("files_number_field")
        self.choose_files_number_label = QtWidgets.QLabel(parent=self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.choose_files_number_label.setFont(font)
        self.choose_files_number_label.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.PreventContextMenu)
        self.choose_files_number_label.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.choose_files_number_label.setStyleSheet("background-color: rgb(214, 214, 214);border-radius: 2.19rem;")
        self.choose_files_number_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.choose_files_number_label.setWordWrap(True)
        self.choose_files_number_label.setObjectName("choose_files_number_label")
        self.files_number_field.addWidget(self.choose_files_number_label)
        self.file_number_field = QtWidgets.QGridLayout()
        self.file_number_field.setObjectName("file_number_field")
        self.many_files_rbtn = QtWidgets.QRadioButton(parent=self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(13)
        self.many_files_rbtn.setFont(font)
        self.many_files_rbtn.setObjectName("many_files_rbtn")
        self.file_number_field.addWidget(self.many_files_rbtn, 2, 0, 1, 1)
        self.single_file_rbtn = QtWidgets.QRadioButton(parent=self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.single_file_rbtn.setFont(font)
        self.single_file_rbtn.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhNoEditMenu)
        self.single_file_rbtn.setObjectName("single_file_rbtn")
        self.file_number_field.addWidget(self.single_file_rbtn, 1, 0, 1, 1)
        self.files_number_field.addLayout(self.file_number_field)
        self.chosen_files_field.addLayout(self.files_number_field)
        self.start_calculating_btn = QtWidgets.QPushButton(parent=self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.start_calculating_btn.setFont(font)
        self.start_calculating_btn.setStyleSheet("background-color: rgb(214, 214, 214);")
        self.start_calculating_btn.setObjectName("start_calculating_btn")
        self.chosen_files_field.addWidget(self.start_calculating_btn)
        self.verticalLayout.addLayout(self.chosen_files_field)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.main_label.setText(_translate("MainWindow", "Добро пожаловать!\n"
"Чтобы загрузить файлы используйте кнопку: \"Выбрать файлы\"\n"
"Чтобы выбрать количество выходных файлов используйте кнопки для выбора\n"
"ВАЖНО! Убедитесь, что выбранные вами файлы не открыты"))
        self.chosen_files_label.setText(_translate("MainWindow", "Выбранные файлы"))
        self.choose_files_btn.setText(_translate("MainWindow", "Выбрать файлы"))
        self.choose_files_number_label.setText(_translate("MainWindow", "Выберите количество выходных файлов"))
        self.many_files_rbtn.setText(_translate("MainWindow", "несколько файлов"))
        self.single_file_rbtn.setText(_translate("MainWindow", "единственный файл"))
        self.start_calculating_btn.setText(_translate("MainWindow", "Начать рассчет"))


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     MainWindow = QtWidgets.QMainWindow()
#     ui = Ui_MainWindow()
#     ui.setupUi(MainWindow)
#     MainWindow.show()
#     sys.exit(app.exec())
